- docker/docker-compose.yml
- src/perception/Dockerfile.Jetson
- src/perception/ros_entrypoint.sh
> Jetson container

- src/perception/docker/Dockerfile
- src/perception/yolo_test/rect.py
- src/perception/yolo_test/requirements_test.py
- src/perception/zed_camera/zed_camera/node_detector.py
Have option for YOLO and OpenCV input for bounding boxes
> Merge YOLO result processing with OpenCV

- src/common/driverless_common/driverless_common/main.py
- src/common/driverless_common/driverless_common/point.py
- src/common/driverless_common/package.xml
- src/common/driverless_common/setup.cfg
- src/common/driverless_common/setup.py
- src/navigation/controllers/controllers/node_simple.py
added point.py so far and tested on `controllers` package. Will add more as we find use
> Merge #42-share-common 

- src/common/driverless_common/driverless_common/node_display.py
- src/common/driverless_common/package.xml
- src/common/driverless_common/setup.py
- src/perception/lidar_pipeline/lidar_pipeline/node_simple.py
- src/perception/vision_pipeline/vision_pipeline/node_detector.py
- src/perception/vision_pipeline/vision_pipeline/node_zed_simulator.py
havent done markers, will use yours
> ROSBoard ConeDetectionStamped displays

- src/navigation/sim_planning/launch/map_pursuit.launch.py
- src/navigation/sim_planning/package.xml
- src/navigation/sim_planning/setup.py
- src/navigation/sim_planning/sim_planning/node_map.py
- src/navigation/sim_planning/sim_planning/node_pursuit.py
- src/navigation/sim_pursuit/launch/local_pursuit.launch.py
- src/navigation/sim_pursuit/setup.py
- src/navigation/sim_pursuit/sim_pursuit/node_find_cones.py
- src/navigation/sim_pursuit/sim_pursuit/node_local_pursuit.py
able to merge - probably doesn't need any development until SLAM is done and we have real maps
> Merge #89 mapped pursuit control

- src/navigation/baby_slam/baby_slam/map_cone.py
- src/navigation/baby_slam/baby_slam/node_slam.py
- src/navigation/baby_slam/baby_slam/rviz_marker.py
- src/navigation/baby_slam/conda_requirements
- src/navigation/baby_slam/package.xml
- src/navigation/baby_slam/setup.cfg
- src/navigation/baby_slam/setup.py
- src/navigation/sim_pursuit/sim_pursuit/node_local_pursuit.py
- src/perception/vision_pipeline/vision_pipeline/node_detector.py
- src/perception/vision_pipeline/vision_pipeline/node_zed_simulator.py
> merge 2 #97 slam 

- src/common/driverless_msgs/msg/State.msg
- src/hardware/steering_actuator/src/node_steering_actuator.cpp
Steering actuator now supports driverless state. The motor will enable on the states: READY, DRIVING, ACTIVATE_EBS, FINISHED, EMERGENCY. All other states the motor will disable.
> Steering Actuator

- src/hardware/canbus/src/TritiumCAN.cpp
- src/hardware/canbus/src/udp_client.cpp
> fix CAN adapter so it properly flushes UDP buffer

- .gitmodules
- src/perception/cpp_lidar/CMakeLists.txt
- src/perception/cpp_lidar/src/dbscan.cpp
- src/perception/cpp_lidar/src/dbscan.h
- src/perception/cpp_lidar/src/node_detector.cpp
Getting faster/more out of it
Still not good enough
> Cpp lidar again

- .pre-commit-config.yaml
- src/navigation/py_slam/py_slam/node_slam.py
> Slam fix 3 feb

- installation/qutms_cli_tools/qutms_cli_tools/main.py
- installation/qutms_cli_tools/setup.cfg
Edited the commands to be more general.
Design B: 
Driverless/Documentation/Software/Infrastructure/QUTMS Command Line Tools
Commands have prefix `ws_<command>`  standing for 'workspace'. Usage is outlined in the screenshot below. Specific commands executed can be found in documentation.
> more general build and launch

- src/navigation/py_slam/package.xml
- src/navigation/py_slam/py_slam/node_odom_slam.py
- src/navigation/py_slam/py_slam/node_sbg_slam.py
- src/navigation/py_slam/setup.py
Created a new node that maps based on an existing location estimation published by a robot_localization node (http://docs.ros.org/en/kinetic/api/robot_localization/html/state_estimation_nodes.html)
See my thesis :) or the link above.
For consistency, we now use ConeDetectionStamped for everything, TrackDetectionStamped is redundant and will be deprecated in the future. 
Anything relying on TrackDetectionStamped should will work just by changing msg type name.
Be aware of the negative euler Z angle. IRL (for now) it's negative so we have to flip it, but from sim its positive. See screenshot below for change. There should be a setting in the SBG that flips it on device (apparently)
> Slam with odom

- src/common/driverless_common/driverless_common/common.py
- src/navigation/planners/planners/node_ordered_mid_spline.py
- src/navigation/planners/setup.py
This orderer and spline planner used to live in `sim_translators` but that pkg is redundant now, so moving it to a dedicate node which will be used not just for sim.
Added `nav_msgs` `Path` message publishing too
Already completed with ordering method was documented
Not from this PR, but identified while working - our custom markers display was removed when we moved to using rviz plugins for cone markers, but this also accidently removed the path line markers. This will be re-added, better than ever, in a new PR but for now, the nav Path message will suffice.
> Ordering planner

- src/navigation/py_slam/py_slam/node_imu_slam.py
- src/navigation/py_slam/py_slam/node_odom_slam.py
- src/navigation/py_slam/py_slam/node_sbg_slam.py
- src/navigation/py_slam/setup.cfg
- tools/topics_to_record/slam.yaml
Comparing slam algorithms for thesis data. Stopped the whole pose history from being published as it was very large.
Thesis :)
The troublesome negative angle - be aware. I think all our nav programs now use 'base_footprint' as the ground-level transform, rather than 'car' which is the vehicle centroid.
n/a
> Slam comparisons

- src/common/driverless_common/driverless_common/common.py
- src/common/driverless_common/driverless_common/marker.py
- src/common/driverless_common/driverless_common/node_display.py
- src/control/path_follower/package.xml
- src/control/path_follower/path_follower/__init__.py
- src/control/path_follower/path_follower/node_pure_pursuit.py
- src/control/path_follower/path_follower/node_pure_pursuit_kdtree.py
- src/control/path_follower/setup.py
- src/control/pure_pursuit_cpp/CMakeLists.txt
- src/control/pure_pursuit_cpp/config/pure_pursuit_cpp.yaml
- src/control/pure_pursuit_cpp/package.xml
- src/control/pure_pursuit_cpp/src/node_pure_pursuit_cpp.cpp
- src/navigation/planners/planners/node_ordered_mid_spline.py
Optimisation
Rewrite the existing python pure pursuit implementation in C++ in search for improved performance. 
Where the python impl runs in 12ms the C++ impl runs in less than 0.2ms. The C++ impl uses the same brute force search (in the `get_rvwp()` method) that the python impl uses. I was able to get the python version down to 3ms using a KDTree to perform the searches, the same technique could be used in the C++ version for further performance improvements.
Please try this out and let me know what you think.
```
colcon build --packages-select pure_pursuit_cpp
ros2 run pure_pursuit_cpp pure_pursuit_cpp
```
Run the sim, diverless_common/display and planners/midline_path nodes with the pure pursuit controller.
In the sim put the car into any drive state, for some reason, this needs to …
> Pure Pursuit In C++

- src/hardware/vehicle_supervisor/CMakeLists.txt
- src/hardware/vehicle_supervisor/src/node_supervisor.cpp
Added Nav Odometry message which encompasses steering rate and velocity for the robot localization odometry filtering.
Comprehensive list of packages, nodes, and topics coming to a doc library near you
N/A
N/A
> wheel odometry

- src/control/path_follower/path_follower/node_pure_pursuit.py
- Updated pure pursuit to use transforms, instead of subscribing to car_pose
- Added a Stanley Controller for velocity control (essentially slows down when turning, speeds up on straights)
IN PROGRESS - `Driverless/Documentation/Software/Navigation/Pure Pursuit (With Stanley Velocity Controller)`
> Pure pursuit upgrade

- tools/ROS_program_info.md
One giant markdown table, broken into each of our package groups, then into nodes and launch files. Made to be easily accessible for quick node or launch referencing (use the markdown view option rather than reading the raw code).
This process has shown how out of date some of our nodes, topics, msgs are and they could very well use a makeover / deprecation
This is the documentation ;) 
Suggestions welcome - deprecated code has intentionally not been explained in as much depth.
> Package list

- tools/qutms_cli_tools/qutms_cli_tools/build.py
- tools/qutms_cli_tools/qutms_cli_tools/common.py
- tools/qutms_cli_tools/qutms_cli_tools/format.py
- tools/qutms_cli_tools/qutms_cli_tools/launch.py
- tools/qutms_cli_tools/qutms_cli_tools/main.py
- tools/qutms_cli_tools/qutms_cli_tools/pull.py
- tools/qutms_cli_tools/qutms_cli_tools/record.py
Workspace format now pre-commit formats all repos we work with (eufs_sim + QUTMS_Driverless at present).
Tidier colourful print statement code.
See Design D:
`Driverless/Documentation/Software/Infrastructure/QUTMS Command Line Tools`
> Cli additions

- src/operations/terminal_control/setup.py
- src/operations/terminal_control/terminal_control/node_state_controller.py
- src/operations/terminal_control/terminal_control/node_state_gui.py
This adds a manual state/mission/lap controller similar to the simulator GUI, but for a terminal interface.
None really, states are already very documented.
> State spoofing

- installation/install_scripts/install_eufs_sim.sh
- installation/setup_conda.sh
- installation/setup_standard.sh
Fixed installation scripts to correctly build qutms_cli_tools / workspace, and to clone the SBG driver into the QUTMS directory.
N/A
N/A
N/A
> Installation

- .gitmodules
- docker/Dockerfile.base
- docker/Dockerfile.jetson_newer
- docker/Dockerfile.roscube
- docker/docker-compose.yml
- docker/roscube_startup.sh
- src/machines/roscube_machine/roscube_requirements.conda
Fix up ROS networking for new jetson LAN connection.
Add nav_integration repo module - future work to copy these in and deprecate development in that repo.
Fix SBG mounting, standard serial dev rules.
https://docs.google.com/document/d/19m3uLLtovWiaIzsZ1k3DOFrNCYlGSvK4GUioXfJtE8g/edit
Requires the container to be rebuilt. No removal of reqs etc
> fix up ROS network. Add nav_integration repo module. fix SBG mounting

- .gitmodules
- src/common/rviz_config/nav2_plan.rviz
- src/common/rviz_config/odom_slam_compare.rviz
- src/common/rviz_config/planning_test.rviz
- src/common/rviz_config/pov.rviz
- src/common/rviz_config/trackdrive.rviz
- src/common/rviz_config/trackdrive_pov.rviz
- src/common/vehicle_urdf/urdf/vehicle.urdf.xacro
- src/control/controllers/controllers/node_sine.py
- src/control/velocity_controller/config/velocity_controller.yaml
- src/control/velocity_controller/src/node_velocity_controller.cpp
- src/hardware/CAN_Common/include/can_interface.hpp
- src/hardware/canbus/CMakeLists.txt
- src/hardware/canbus/src/node_canbus_translator.cpp
- src/hardware/canbus/src/node_canbus_translator_socket.cpp
- src/hardware/vehicle_supervisor/CMakeLists.txt
- src/hardware/vehicle_supervisor/src/node_supervisor_slim.cpp
- src/perception/lidar_pipeline/lidar_pipeline/node_lidar_detector.py
- tools/colcon_ignore.yaml
- tools/topics_to_record/slam_carpark.yaml
Updates from comp. Includes EBS control state changes, velocity controller rate limiter.
Other misc additions and updates.
Removed YOLOv5 repo (should have been removed with the detector)
> Comp updates

- tools/colcon_ignore.yaml
> Update colcon ignore so that people can build

- src/common/driverless_common/driverless_common/shutdown_node.py
- src/hardware/vehicle_supervisor/CMakeLists.txt
- src/hardware/vehicle_supervisor/src/node_supervisor.cpp
- src/hardware/vehicle_supervisor/src/node_supervisor_slim.cpp
- src/machines/roscube_machine/launch/machine.launch.py
- src/operations/mission_controller/mission_controller/node_trackdrive_handler.py
Twofold change, single feature. This brings in code from `vehicle_supervisor_slim` into `vehicle_supervisor` overwriting outdated code.
`vehicle_supervisor` was then expanded (separating it from `slim`) to include mission launching with system calls. This would remove the need for the separate `mission_launcher` node.
Rev E - `Driverless/Documentation/Software/Infrastructure/Vehicle State Control`
No breaking changes, two node options to use (slim, or standard with launching)
> Mission startups

- src/hardware/sbg_translator/include/node_sbg_translator.hpp
- src/hardware/sbg_translator/src/node_sbg_translator.cpp
Refactor
Split SBG translator node in to a .cpp and a .hpp to improve compilation performance.
No existing documentation has changed.
> Split node_sbg_translator.cpp into a hpp and a cpp.

- docker/Dockerfile.roscube
- src/navigation/nav_bringup/config/localisation_params.yaml
- src/navigation/planners/config/ft_planner.yaml
- src/navigation/planners/planners/node_ft_planner.py
- src/navigation/planners/setup.py
- src/operations/mission_controller/launch/trackdrive.launch.py
Added a new path planner implementation. Used by TU Berlin (FaSTTUBe) for global planning within a search window in front of the vehicle. This adds a ROS wrapper around the planner object:
- Subscribes to cone map, car pose TF
- Publishes path, boundaries, occupancy grid map of boundaries
Explanation on how this works:
https://papalotis-ft-fsd-path-planning-streamlit-main-63xmrt.streamlit.app/
N/a
> Planning revamp

- tools/ssh_connection.sh
Ease of access for the remote ssh connection into the car -> user input to either 'rasbipi,' 'roscube,' or 'jetson.' 
https://docs.google.com/document/d/1MmFTtyRppXqyWelj_COYUsaF81bytKuAtvTLVzLHFzM/edit?usp=drive_link
none that are known as of yet
> Ssh connection

- src/machines/roscube_machine/launch/foxglove.launch.py
- src/machines/roscube_machine/launch/machine.launch.py
- tools/telemetry_dashboards/main_dashboard.json
- tools/telemetry_dashboards/multi-page-dash.json
JavaScript for Foxglove Telemetry Dashboard layout. Contains settings and layout specifications for main Foxglove dashboard. Use to import pre-designed dashboard into Foxglove for real and post time data telemetry. 
https://docs.google.com/document/d/1JXh5C6tzqSkOcdFvKujXUXc-JR84JVB9_n0gXdFBjkQ/edit?usp=drive_link
Dashboard Layout:
> Dashboards

- src/navigation/slam_gridmap/package.xml
- src/navigation/slam_gridmap/setup.cfg
- src/navigation/slam_gridmap/setup.py
- src/navigation/slam_gridmap/slam_gridmap/node_gridmap_to_code_detection.py
- src/navigation/slam_gridmap/test/test_copyright.py
- src/navigation/slam_gridmap/test/test_flake8.py
- src/navigation/slam_gridmap/test/test_pep257.py
- src/perception/lidar_pipeline/lidar_pipeline/node_lidar_detector.py
!UNTESTED!
using SLAM gridmap to detect cones (2D)
use of LiDAR DBSCAN point clustering process
This script takes the SLAM gridmap that gets created, recognizes and clusters points using DBSCAN
the clustered points then get recognised as cones if they are within certain parameters
the gridmap get a new origin point with each update the map gets
https://www.notion.so/qut-motorsports/SLAM-Cone-Detection-9b6e0e06287b4d12b28a27e52a949ccd
None
(cone overlay onto SLAM toolbox gridmap)
> SLAM_cone_detection (with description)

- src/common/vehicle_urdf/urdf/sensors.urdf.xacro
- src/operations/mission_controller/launch/ebs_test.launch.py
- src/operations/mission_controller/mission_controller/node_ebs_test_handler.py
- tools/play_bag.sh
Previous testing of control in a local reference frame for EBS test has proven limited. Hoping for more stable control with a global reference frame given improvements to SLAM and cone mapping.
Not a feature - param changes documented in config and launch files
None
> EBS test nav
